FROM node:22-bookworm AS build
ENV NODE_ENV=production
ENV VITE_API_ENDPOINT=/api

COPY --chown=node:node ./frontend /opt/citybus-frontend
WORKDIR /opt/citybus-frontend
RUN npm run build

FROM nginx:stable-bookworm

RUN rm -rf /usr/share/nginx/html
COPY --from=build /opt/citybus-frontend/dist /usr/share/nginx/html
COPY ./deployment_configs/default.conf.frontend /etc/nginx/conf.d/default.conf
