FROM node:22-bookworm

COPY --chown=node:node ./api /opt/citybus-api
WORKDIR /opt/citybus-api
RUN npm install

ENV NODE_ENV=production
ENV LISTEN_PORT=80
ENV WS_ENDPOINT=http://127.0.0.1:80

ENTRYPOINT [ "npm", "start" ]
