name: citybus
networks:
  default:
    driver: bridge
  osrm-backend:
    internal: true

services:
  dev:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ../:/code
    entrypoint: /bin/bash
    tty: true
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      APP_SECRET: 26sf0PRZwuaYWJ0wF6L8mv6jnro8dC45
      MONGODB_URL: mongodb://root:password@mongo:27017/citybus?authSource=admin&directConnection=true
      LOGGING_LEVEL: DEBUG
      VITE_API_ENDPOINT: /api
    networks:
        - default

  mongo:
    image: bitnami/mongodb:8.0
    restart: unless-stopped
    user: 0:0
    volumes:
      - ./mongo:/bitnami/mongodb
      - ./mongo-scripts/init.sh:/docker-entrypoint-initdb.d/01-init.sh
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rsCitybus
      MONGODB_ADVERTISED_HOSTNAME: mongo
      MONGODB_REPLICA_SET_KEY: k5ByQYbhd6m7HuuzSdOU9adlaTqSiMVf
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: password
    networks:
      - default


  express:
    image: mongo-express:1.0.2-20
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/?directConnection=true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH: false
    networks:
      - default

  osrm:
    image: nginx:1.27
    restart: unless-stopped
    volumes:
      - ./nginx-osrm.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
      - osrm-backend
  osrm-foot-backend:
    image: osrm/osrm-backend
    restart: unless-stopped
    entrypoint: osrm-routed --algorithm mld --port 80 --ip 0.0.0.0 /data/osrm/foot/data.osrm
    volumes:
      - ./osrm:/data/osrm
    networks:
      - osrm-backend
  osrm-car-backend:
    image: osrm/osrm-backend
    restart: unless-stopped
    entrypoint: osrm-routed --algorithm mld --port 80 --ip 0.0.0.0 /data/osrm/car/data.osrm
    volumes:
      - ./osrm:/data/osrm
    networks:
      - osrm-backend

  redis:
    image: redis:7.4
    restart: unless-stopped
    networks:
      - default
