name: citybus
networks:
  default:
    driver: bridge
  osrm-backend:
    internal: true

services:
  dev:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ../:/code
    entrypoint: /bin/bash
    tty: true
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      APP_SECRET: 26sf0PRZwuaYWJ0wF6L8mv6jnro8dC45
      MONGODB_URL: mongodb://mongo:27017/citybus
      LOGGING_LEVEL: DEBUG
      VITE_API_ENDPOINT: /api
    networks:
        - default

  mongo:
    image: bitnami/mongodb:8.0
    restart: unless-stopped
    user: 0:0
    volumes:
      - ./mongo:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rsCitybus
      ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - default


  express:
    image: mongo-express:1.0.2-20
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/citybus
      ME_CONFIG_BASICAUTH: false
    networks:
      - default

  osrm:
    image: nginx:1.27
    restart: unless-stopped
    volumes:
      - ./nginx-osrm.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
      - osrm-backend
  osrm-foot-backend:
    image: osrm/osrm-backend
    restart: unless-stopped
    entrypoint: osrm-routed --algorithm mld --port 80 --ip 0.0.0.0 /data/osrm/foot/data.osrm
    volumes:
      - ./osrm:/data/osrm
    networks:
      - osrm-backend
  osrm-car-backend:
    image: osrm/osrm-backend
    restart: unless-stopped
    entrypoint: osrm-routed --algorithm mld --port 80 --ip 0.0.0.0 /data/osrm/car/data.osrm
    volumes:
      - ./osrm:/data/osrm
    networks:
      - osrm-backend

  redis:
    image: redis:7.4
    restart: unless-stopped
    networks:
      - default
