openapi: '3.0.3'

info:
  title: CityBus API
  version: '1.0'

servers:
  - url: 127.0.0.1:3001

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    400BadRequest:
      description: Request not valid
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MessageResponse"
    401Unauthorized:
      description: Client not authenticated
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MessageResponse"
    403Forbidden:
      description: Client not allowed to access resource
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MessageResponse"
    404NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MessageResponse"
    500InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MessageResponse"
  schemas:
    MessageResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    User:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        role:
          type: string
    GeoJSONPoint:
      type: object
      properties:
        type:
          type: string
          enum:
            - Point
        coordinates:
          type: array
          items:
            type: number
          minLength: 2
          maxLength: 2
          example: [30.140484, -9.156697]
    GeoJSONLineString:
      type: object
      properties:
        type:
          type: string
          enum:
            - LineString
        coordinates:
          type: array
          example: [30.140484, -9.156697]
          items:
            type: array
            minLength: 2
            maxLength: 2
            items:
              type: number
    RouteStep:
      type: object
      properties:
        duration:
          type: number
        geometry:
          type: array
          items:
            $ref: "#/components/schemas/GeoJSONLineString"
    RouteLeg:
      type: object
      properties:
        duration:
          type: number
        steps:
          type: array
          items:
            $ref: "#/components/schemas/RouteStep"
    NavigationFootLeg:
      type: object
      properties:
        type:
          type: string
          enum:
            - foor
        duration:
          type: number
        departureTimestamp:
          type: number
        arrivalTimestamp:
          type: number
        steps:
          type: array
          items:
            $ref: "#/components/schemas/GeoJSONLineString"
    NavigationBusLeg:
      type: object
      properties:
        type:
          type: string
          enum:
            - "bus"
        duration:
          type: number
        departureTimestamp:
          type: number
        arrivalTimestamp:
          type: number
        stops:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              timeToNext:
                type: number
              routeToNext:
                type: array
                items:
                  $ref: "#/components/schemas/GeoJSONLineString"
    FullBusLine:
      type: object
      properties:
        name:
          type: string
        directions:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              stops:
                type: array
                items:
                  oneOf:
                    - type: string
                    - type: object
                      properties:
                        name:
                          type: string
                        location:
                          $ref: "#/components/schemas/GeoJSONPoint"
              routeLegs:
                type: array
                items:
                  $ref: "#/components/schemas/RouteLeg"
              timetable:
                type: array
                items:
                  type: array
                  items:
                    type: string

tags:
  - name: authentication
    description: Users' authentication
  - name: user
    description: User profile
  - name: routes
    description: Routing engine interface
  - name: busline
    description: Bus lines, directions and stops

paths:
  /auth/session:
    post:
      summary: Authenticate user and create new session
      tags:
        - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '201':
          description: JSON containing user's informations, JWT and renew token
          content:
            application/json:
              schema:
                type: object
                properties:
                  jwt:
                    type: string
                  renewToken:
                    type: string
                required:
                  - jwt
                  - renewToken
        '400':
          $ref: "#/components/responses/400BadRequest"
        '401':
          $ref: "##/components/responses/401Unauthorized"
        '500':
          $ref: "#/components/responses/500InternalServerError"
    put:
      summary: Renew current session and receive new tokens
      tags:
        - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                renewToken:
                  type: string
              required:
                - renewToken
      responses:
        '200':
          description: JSON containing new JWT and renew token
          content:
            application/json:
              schema:
                type: object
                properties:
                  jwt:
                    type: string
                  renewToken:
                    type: string
                required:
                  - jwt
                  - renewToken
        '401':
          $ref: "#/components/responses/401Unauthorized"
  /auth/password:
    put:
      summary: Update user's password
      tags:
        - authentication
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                oldPassword:
                  type: string
                newPassword:
                  type: string
              required:
                - oldPassword
                - newPassword
      responses:
        "200":
          description: Password changed successfully
        "403":
          $ref: "#/components/responses/403Forbidden"
        '500':
          $ref: "#/components/responses/500InternalServerError"

  /user:
    get:
      summary: Get logged user's informations
      tags:
        - user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: JSON containing user informations
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '401':
          $ref: "#/components/responses/401Unauthorized"
        '500':
          $ref: "#/components/responses/500InternalServerError"
    put:
      summary: Update user's informations
      tags:
        - user
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
              required:
                - firstName
                - lastName
      responses:
        '200':
          description: User updated
        '400':
          $ref: "#/components/responses/400BadRequest"
        '401':
          $ref: "#/components/responses/401Unauthorized"
        '500':
          $ref: "#/components/responses/500InternalServerError"

  /routes/busline:
    get:
      summary: Generate route for a new bus line using specified coordinates as stops
      tags:
        - routes
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: stops
          schema:
            type: string
          description: List of stops coordinates in format longitude,latitude separated by ;
          required: true
      responses:
        '200':
          description: Return an array where each element is the route between one stop and the next one; array elements order is based on stops order in request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RouteLeg"
        '400':
          $ref: "#/components/responses/400BadRequest"
        '401':
          $ref: "#/components/responses/401Unauthorized"
        '403':
          $ref: "#/components/responses/403Forbidden"
        '500':
          $ref: "#/components/responses/500InternalServerError"
  /routes/navigation:
    get:
      summary: Generate navigation route between two points combining walking paths and bus lines
      tags:
        - routes
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: departure_timestamp
          schema:
            type: number
          description: The departure timestamp
          required: true
      responses:
        '200':
            description: "TODO: write description"
            content:
              application/json:
                schema:
                  type: array
                  items:
                    oneOf:
                      - $ref: "#/components/schemas/NavigationFootLeg"
                      - $ref: "#/components/schemas/NavigationBusLeg"
        '400':
          $ref: "#/components/responses/400BadRequest"
        '401':
          $ref: "#/components/responses/401Unauthorized"
        '403':
          $ref: "#/components/responses/403Forbidden"
        '500':
          $ref: "#/components/responses/500InternalServerError"

  /buslines:
    get:
      summary: Retrieve list of bus lines
      tags:
        - busline
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: Optional search query to filter lines
          required: false
      responses:
        '200':
          description: "List of bus lines"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
        '401':
          $ref: "#/components/responses/401Unauthorized"
        '500':
          $ref: "#/components/responses/500InternalServerError"
    post:
      summary: Create new bus line
      tags:
        - busline
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FullBusLine"
      responses:
        '201':
          description: "Resource created successfully"
        '400':
          $ref: "#/components/responses/400BadRequest"
        '401':
          $ref: "#/components/responses/401Unauthorized"
        '403':
          $ref: "#/components/responses/403Forbidden"
        '500':
          $ref: "#/components/responses/500InternalServerError"
  /buslines/{busLineId}:
    put:
      summary: Update existing bus line
      tags:
        - busline
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: busLineId
          schema:
            type: string
          required: true
          description: Id of the bus line
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FullBusLine"
      responses:
        '200':
          description: "Resource updated successfully"
        '400':
          $ref: "#/components/responses/400BadRequest"
        '401':
          $ref: "#/components/responses/401Unauthorized"
        '403':
          $ref: "#/components/responses/403Forbidden"
        '404':
          $ref: "#/components/responses/404NotFound"
        '500':
          $ref: "#/components/responses/500InternalServerError"
  /buslines/{busLineId}/directions:
    get:
      summary: Get all available directions for specified bus line
      tags:
        - busline
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: busLineId
          schema:
            type: string
          required: true
          description: Id of the bus line
      responses:
        '200':
          description: List of directions for specified bus line
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
        '401':
          $ref: "#/components/responses/401Unauthorized"
        '404':
          $ref: "#/components/responses/404NotFound"
        '500':
          $ref: "#/components/responses/500InternalServerError"
  /buslines/{busLineId}/directions/{directionId}/timetable:
    get:
      summary: Get timetable for specified line and direction
      tags:
        - busline
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: busLineId
          schema:
            type: string
          required: true
          description: Id of the bus line
        - in: path
          name: directionId
          schema:
            type: string
          required: true
          description: Id of the direction
      responses:
        '200':
          description: Timetable for specified line and direction
          content:
            application/json:
              schema:
                type: object
                properties:
                  stops:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                  timetable:
                    type: array
                    items:
                      type: array
                      items:
                        type: string
        '401':
          $ref: "#/components/responses/401Unauthorized"
        '404':
          $ref: "#/components/responses/404NotFound"
        '500':
          $ref: "#/components/responses/500InternalServerError"


